'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { AppShell } from '@/components/app-shell';
import { ListingCard } from '@/components/listing-card';
import { Badge, Button, Card, EmptyState, Field, Notice, PageHeader, QueryFailed, Skeleton, inputClass } from '@/components/ui';
import { trpc } from '@/lib/trpc/client';
import { useUzzCommunityId } from '@/lib/use-uzz-community';
import { bankHeadline, bankHopsLabel, bankStatusLabel, hadUzzSession, tomorrowNominal, uzzErrorMessage } from '@/lib/utils';

type Tab = 'rights' | 'listings' | 'deeds';
export default function HomePage() {
  const { communityId, loggedIn, sessionLoading } = useUzzCommunityId(); const [tab, setTab] = useState<Tab>('rights');
  useEffect(() => { const value = new URLSearchParams(window.location.search).get('tab'); if (value === 'lots') setTab('listings'); if (value === 'deeds') setTab('deeds'); }, []);
  if (sessionLoading) return <AppShell><Skeleton className="h-64" /></AppShell>;
  if (!loggedIn) return <AppShell><Guest expired={hadUzzSession()} /></AppShell>;
  return <AppShell><div className="space-y-8"><PageHeader eyebrow="Личный раздел" title="Моё">Ваши права на обмен, предложения и добрые дела — разные сущности. Здесь они показаны отдельно, без путаницы с кошельком заслуг.</PageHeader>
    <div role="tablist" className="inline-flex max-w-full gap-1 overflow-x-auto rounded-xl border border-stitch-border bg-stitch-surface p-1">{([['rights', 'Права'], ['listings', 'Мои услуги'], ['deeds', 'Добрые дела']] as const).map(([id, label]) => <button key={id} role="tab" aria-selected={tab === id} onClick={() => setTab(id)} className={`min-h-10 whitespace-nowrap rounded-lg px-4 text-sm font-semibold ${tab === id ? 'bg-stitch-accent text-white' : 'text-stitch-muted'}`}>{label}</button>)}</div>
    {tab === 'rights' ? <Rights communityId={communityId} /> : tab === 'listings' ? <Listings communityId={communityId} /> : <Deeds communityId={communityId} />}
  </div></AppShell>;
}

function Guest({ expired }: { expired: boolean }) { return <div className="space-y-8"><PageHeader eyebrow="Обмен внутри сообщества" title={expired ? 'Сессия истекла' : 'Доброе дело превращается в возможность попросить о помощи'}>{expired ? 'Войдите снова по одноразовой ссылке из письма.' : 'Это не деньги: сообщество признаёт вклад, администратор назначает предел обмена, а право постепенно тает и переходит между людьми.'}</PageHeader><div className="flex flex-wrap gap-2"><Link href="/catalog" className="rounded-xl bg-stitch-accent px-4 py-3 text-sm font-semibold text-white">Смотреть услуги</Link><Link href="/login?next=/" className="rounded-xl border border-stitch-border px-4 py-3 text-sm font-semibold">Войти по email</Link></div><div className="grid gap-4 sm:grid-cols-3">{[['1', 'Сделайте доброе дело', 'Расскажите о нём в Telegram-сообществе.'], ['2', 'Получите право', 'После порога заслуг администратор назначит номинал.'], ['3', 'Обменяйтесь', 'Выберите услугу; контакт откроется после принятия.']].map(([n, title, copy]) => <Card key={n}><Badge tone="accent">Шаг {n}</Badge><h2 className="mt-3 font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-stitch-muted">{copy}</p></Card>)}</div></div>; }

function Rights({ communityId }: { communityId: string }) {
  const rights = trpc.banks.listMine.useQuery({ communityId }, { retry: false }); const settings = trpc.settings.get.useQuery({ communityId }, { retry: false });
  if (rights.isLoading) return <Skeleton className="h-56" />; if (rights.isError) return <QueryFailed onRetry={() => void rights.refetch()} />; if (!rights.data?.length) return <EmptyState title="Прав пока нет">Когда доброе дело наберёт установленный порог заслуг, здесь появится право на обмен.</EmptyState>;
  return <ul className="grid gap-4 md:grid-cols-2">{rights.data.map((right) => { const tomorrow = tomorrowNominal(right.nominalRub, settings.data?.demurrageRubPerDay ?? 100, settings.data?.nominalFloorRub ?? 100); return <li key={right.id}><Card><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-black">{right.sourceTitle || 'Право на обмен'}</h2><p className="mt-1 text-sm text-stitch-muted">{bankHeadline(right)}</p></div><Badge tone={right.status === 'active' ? 'ok' : right.status === 'in_deal' ? 'warn' : 'neutral'}>{bankStatusLabel(right.status)}</Badge></div><div className="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-stitch-canvas/60 p-4 text-sm"><div><p className="text-xs text-stitch-muted">Переходы</p><p className="font-semibold">{bankHopsLabel(right.hopsLeft)}</p></div><div><p className="text-xs text-stitch-muted">Завтра</p><p className="font-semibold">{tomorrow == null ? '—' : `${tomorrow} ₽`}</p></div></div>{right.nominalRub === (settings.data?.nominalFloorRub ?? 100) ? <p className="mt-3 text-xs text-stitch-muted">Достигнут нижний предел: право продолжает действовать и не исчерпывается из-за номинала.</p> : null}</Card></li>; })}</ul>;
}

function Listings({ communityId }: { communityId: string }) {
  const utils = trpc.useUtils(); const listings = trpc.lots.myLots.useQuery({ communityId }, { retry: false }); const [showForm, setShowForm] = useState(false); const [error, setError] = useState<string | null>(null);
  const create = trpc.lots.create.useMutation({ onSuccess: () => { setShowForm(false); setError(null); void Promise.all([utils.lots.myLots.invalidate(), utils.lots.list.invalidate(), utils.lots.canBuy.invalidate()]); }, onError: (err) => setError(uzzErrorMessage(err)) }); const update = trpc.lots.update.useMutation({ onSuccess: () => { void Promise.all([utils.lots.myLots.invalidate(), utils.lots.list.invalidate()]); }, onError: (err) => setError(uzzErrorMessage(err)) });
  return <div className="space-y-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">Ваши предложения</h2><p className="text-sm text-stitch-muted">Три карточки по умолчанию — рекомендация, а не запрет.</p></div><Button onClick={() => setShowForm((value) => !value)}>{showForm ? 'Закрыть форму' : 'Добавить услугу'}</Button></div>{showForm ? <CreateListing pending={create.isPending} error={error} onSubmit={(data) => create.mutate({ communityId, ...data })} /> : null}{listings.isLoading ? <Skeleton className="h-48" /> : listings.isError ? <QueryFailed onRetry={() => void listings.refetch()} /> : !listings.data?.length ? <EmptyState title="Предложений пока нет">Добавьте то, чем готовы помочь сообществу.</EmptyState> : <ul className="grid gap-4 md:grid-cols-2">{listings.data.map((item) => <li key={item.id} className={!item.active ? 'opacity-60' : ''}><ListingCard listing={item} own /><Button className="mt-2 w-full" variant="ghost" disabled={update.isPending} onClick={() => update.mutate({ lotId: item.id, active: !item.active })}>{item.active ? 'Скрыть из каталога' : 'Вернуть в каталог'}</Button></li>)}</ul>}</div>;
}

function CreateListing({ pending, error, onSubmit }: { pending: boolean; error?: string | null; onSubmit: (value: { title: string; description?: string; priceRub: number; deliveryMode: 'online' | 'offline' | 'both'; locationText?: string; durationText?: string; availabilityText?: string }) => void }) {
  const [form, setForm] = useState({ title: '', description: '', priceRub: '500', deliveryMode: 'online' as const, locationText: '', durationText: '', availabilityText: '' });
  function submit(event: FormEvent) { event.preventDefault(); onSubmit({ ...form, priceRub: Number(form.priceRub), description: form.description || undefined, locationText: form.locationText || undefined, durationText: form.durationText || undefined, availabilityText: form.availabilityText || undefined }); }
  const field = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <Card><form className="space-y-4" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><Field label="Название"><input required minLength={3} maxLength={120} className={inputClass} value={form.title} onChange={(event) => field('title', event.target.value)} /></Field><Field label="Цена, ₽"><input required type="number" min={1} className={inputClass} value={form.priceRub} onChange={(event) => field('priceRub', event.target.value)} /></Field><Field label="Формат"><select className={inputClass} value={form.deliveryMode} onChange={(event) => setForm((current) => ({ ...current, deliveryMode: event.target.value as typeof form.deliveryMode }))}><option value="online">Онлайн</option><option value="offline">Очно</option><option value="both">Онлайн или очно</option></select></Field><Field label="Длительность"><input maxLength={120} className={inputClass} value={form.durationText} onChange={(event) => field('durationText', event.target.value)} placeholder="Например, 60 минут" /></Field><Field label="Место"><input maxLength={160} className={inputClass} value={form.locationText} onChange={(event) => field('locationText', event.target.value)} /></Field><Field label="Доступность"><input maxLength={500} className={inputClass} value={form.availabilityText} onChange={(event) => field('availabilityText', event.target.value)} placeholder="Вечерами по будням" /></Field></div><Field label="Описание"><textarea rows={4} maxLength={2000} className={inputClass} value={form.description} onChange={(event) => field('description', event.target.value)} /></Field>{error ? <Notice tone="warn">{error}</Notice> : null}<Button type="submit" disabled={pending}>{pending ? 'Сохраняем…' : 'Опубликовать'}</Button></form></Card>;
}

function Deeds({ communityId }: { communityId: string }) { const deeds = trpc.deeds.list.useQuery({ communityId }, { retry: false }); if (deeds.isLoading) return <Skeleton className="h-48" />; if (deeds.isError) return <QueryFailed onRetry={() => void deeds.refetch()} />; if (!deeds.data?.length) return <EmptyState title="Добрых дел пока нет" />; return <ul className="space-y-3">{deeds.data.map((deed) => <li key={deed.publicationId}><Card><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-black">{deed.title}</h2><p className="mt-1 text-sm text-stitch-muted">{deed.score} из {deed.emissionThreshold} заслуг</p></div>{deed.bankStatus ? <Badge tone="ok">Право создано</Badge> : <Badge>{Math.round(deed.progress * 100)}%</Badge>}</div><div className="mt-4 h-2 overflow-hidden rounded-full bg-stitch-canvas"><div className="h-full rounded-full bg-stitch-accent" style={{ width: `${Math.round(deed.progress * 100)}%` }} /></div></Card></li>)}</ul>; }
