import { z } from 'zod';

/** Canonical notification type literals (mirrors Mongoose NotificationSchemaClass.type enum). */
export const NotificationTypeSchema = z.enum([
  'vote',
  'beneficiary',
  'mention',
  'reply',
  'comment',
  'publication',
  'poll',
  'favorite_update',
  'system',
  'quota',
  'forward_proposal',
  'team_join_request',
  'team_invitation',
  'investment_received',
  'investment_distributed',
  'post_closed_investment',
  'investment_pool_depleted',
  'post_closed',
  'post_ttl_warning',
  'post_inactivity_warning',
  'project_created',
  'ticket_assigned',
  'ticket_done',
  'ticket_assignee_declined',
  'ticket_accepted',
  'ticket_returned_for_revision',
  'ticket_evaluated',
  'project_published',
  'project_distributed',
  'project_closed',
  'member_joined',
  'member_left_project',
  'shares_changed',
  'ticket_apply',
  'ticket_rejection',
  'ob_vote_join_offer',
  'project_parent_link_requested',
  'project_parent_link_approved',
  'project_parent_link_rejected',
  'community_member_removed',
  'event_created',
  'event_invitation',
  'document_variant_proposed',
  'document_variant_not_selected',
  'document_variant_won',
  'document_variant_applied',
  'document_block_admin_override',
]);

export type NotificationType = z.infer<typeof NotificationTypeSchema>;
