'use client';

import { useEffect, useState } from 'react';
import { AdminCommunityForm } from '@/components/admin-community-form';
import { AdminSettingsForm } from '@/components/admin-settings-form';
import { AppShell } from '@/components/app-shell';
import { Badge, Button, Card, EmptyState, Field, Notice, PageHeader, QueryFailed, Skeleton, inputClass } from '@/components/ui';
import { trpc } from '@/lib/trpc/client';
import { useUzzCommunityId } from '@/lib/use-uzz-community';
import { bankStatusLabel, dealStatusLabel, formatWhen, INTEGER_RUBLES_MESSAGE, ledgerTypeLabel, parseIntegerRubles, uzzErrorMessage, walletSourceLabel } from '@/lib/utils';

export default function AdminPage() {
  const { communityId, isUzzAdmin, loggedIn } = useUzzCommunityId(); const enabled = Boolean(communityId) && loggedIn && isUzzAdmin; const utils = trpc.useUtils();
  const settings = trpc.settings.get.useQuery({ communityId }, { enabled, retry: false }); const communities = trpc.community.listMine.useQuery(undefined, { enabled, retry: false }); const awaiting = trpc.banks.listAwaitingNominal.useQuery({ communityId }, { enabled, retry: false }); const holding = trpc.banks.listHolding.useQuery({ communityId }, { enabled, retry: false }); const deals = trpc.deals.adminList.useQuery({ communityId }, { enabled, retry: false });
  const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [nominals, setNominals] = useState<Record<string, string>>({}); const [resolution, setResolution] = useState<{ id: string; outcome: 'close' | 'cancel'; reason: string } | null>(null);
  const [ledgerCursor, setLedgerCursor] = useState<{ createdAt: Date | string; id: string } | undefined>(undefined);
  const [ledgerItems, setLedgerItems] = useState<Array<{ id: string; type: string; amount: number; createdAt: Date | string; metadata?: Record<string, unknown> }>>([]);
  const ledger = trpc.ledger.list.useQuery({ communityId, limit: 30, cursor: ledgerCursor }, { enabled, retry: false });
  useEffect(() => {
    if (!ledger.data) return;
    setLedgerItems((current) => {
      const incoming = ledger.data.items;
      if (!ledgerCursor) return incoming;
      const seen = new Set(current.map((row) => row.id));
      return [...current, ...incoming.filter((row) => !seen.has(row.id))];
    });
  }, [ledger.data, ledgerCursor]);
  const ok = (message: string) => { setNotice(message); setError(null); setLedgerCursor(undefined); setLedgerItems([]); void Promise.all([utils.settings.get.invalidate(), utils.banks.listAwaitingNominal.invalidate(), utils.deals.adminList.invalidate(), utils.ledger.list.invalidate()]); }; const failed = (err: { message?: string }) => setError(uzzErrorMessage(err));
  const update = trpc.settings.update.useMutation({ onSuccess: () => ok('Настройки сохранены.'), onError: failed }); const setStand = trpc.community.setStand.useMutation({ onSuccess: () => { window.location.reload(); }, onError: failed }); const nominal = trpc.banks.setNominal.useMutation({ onSuccess: () => ok('Номинал назначен.'), onError: failed }); const adminClose = trpc.deals.adminClose.useMutation({ onSuccess: () => { setResolution(null); ok('Сделка принудительно закрыта.'); }, onError: failed }); const adminCancel = trpc.deals.adminCancel.useMutation({ onSuccess: () => { setResolution(null); ok('Сделка отменена, резерв возвращён.'); }, onError: failed });
  if (loggedIn && !isUzzAdmin) return <AppShell><EmptyState title="Нужны права администратора">Этот раздел доступен администратору выбранного сообщества.</EmptyState></AppShell>;
  return <AppShell><div className="space-y-8"><PageHeader eyebrow="Настройки платформы" title="Настройки и контроль">Все критичные параметры доступны здесь. Администраторские решения по сделкам требуют письменной причины и попадают в журнал.</PageHeader>{notice ? <Notice tone="ok">{notice}</Notice> : null}{error ? <Notice tone="warn">{error}</Notice> : null}
    {communities.isLoading ? <Skeleton className="h-40" /> : communities.isError ? <QueryFailed onRetry={() => void communities.refetch()} error={communities.error} /> : <AdminCommunityForm communities={communities.data?.communities ?? []} selectedCommunityId={communities.data?.selectedCommunityId || communityId} pending={setStand.isPending} error={setStand.error ? uzzErrorMessage(setStand.error) : null} onSave={(nextCommunityId) => setStand.mutate({ communityId: nextCommunityId })} />}
    {settings.isLoading ? <Skeleton className="h-96" /> : settings.isError ? <QueryFailed onRetry={() => void settings.refetch()} error={settings.error} /> : <AdminSettingsForm settings={settings.data} pending={update.isPending} error={update.error ? uzzErrorMessage(update.error) : null} onSave={(patch) => update.mutate({ commandId: crypto.randomUUID(), communityId, patch })} />}
    <section className="space-y-4"><div><h2 className="text-xl font-black">Назначение номинала</h2><p className="text-sm text-stitch-muted">Банк становится активным только после назначения суммы.</p></div>{awaiting.isLoading ? <Skeleton className="h-32" /> : awaiting.isError ? <QueryFailed onRetry={() => void awaiting.refetch()} error={awaiting.error} /> : !awaiting.data?.length ? <EmptyState title="Очередь пуста" /> : <ul className="grid gap-3 md:grid-cols-2">{awaiting.data.map((right) => { const raw = nominals[right.id] ?? ''; const parsed = parseIntegerRubles(raw); const floor = settings.data?.nominalFloorRub ?? 1; const invalidInteger = raw !== '' && parsed == null; return <li key={right.id}><Card><div className="flex items-start justify-between gap-3"><div><h3 className="font-extrabold">{right.ownerName}</h3><p className="mt-1 text-sm text-stitch-muted">{right.sourceTitle || 'Доброе дело'} · {right.sourceScore ?? 0} заслуг</p></div><Badge>{bankStatusLabel(right.status)}</Badge></div><div className="mt-4 space-y-2"><div className="flex gap-2"><input aria-label="Номинал в рублях" type="number" min={floor} step={1} value={raw} onChange={(event) => setNominals((current) => ({ ...current, [right.id]: event.target.value }))} className={inputClass} placeholder="Номинал, ₽" /><Button disabled={nominal.isPending || parsed == null || parsed < floor} onClick={() => { if (parsed == null) return; nominal.mutate({ commandId: crypto.randomUUID(), bankId: right.id, nominalRub: parsed }); }}>Назначить</Button></div>{invalidInteger ? <p className="text-sm text-amber-200">{INTEGER_RUBLES_MESSAGE}</p> : null}</div></Card></li>; })}</ul>}</section>
    {holding.data?.length ? <Notice tone="info"><strong>Ждут привязку профиля: {holding.data.length}.</strong> Эти банки автоматически перейдут в очередь номиналов после связывания email и Telegram.</Notice> : null}
    <section className="space-y-4"><div><h2 className="text-xl font-black">Открытые сделки</h2><p className="text-sm text-stitch-muted">Вмешивайтесь только в спорных случаях: обычные сделки закрываются участниками или автоматически.</p></div>{deals.isLoading ? <Skeleton className="h-40" /> : deals.isError ? <QueryFailed onRetry={() => void deals.refetch()} error={deals.error} /> : !deals.data?.length ? <EmptyState title="Открытых сделок нет" /> : <ul className="space-y-3">{deals.data.map((deal) => <li key={deal.id}><Card><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-extrabold">{deal.listingSnapshot.title}</h3><p className="text-sm text-stitch-muted">{dealStatusLabel(deal.status)} · создана {formatWhen(deal.createdAt)}</p></div><div className="flex gap-2"><Button variant="ghost" onClick={() => setResolution({ id: deal.id, outcome: 'close', reason: '' })}>Закрыть</Button><Button variant="danger" onClick={() => setResolution({ id: deal.id, outcome: 'cancel', reason: '' })}>Отменить</Button></div></div>{resolution?.id === deal.id ? <div className="mt-4 space-y-3 border-t border-stitch-border pt-4"><Field label="Причина решения" hint="Не менее 10 символов; будет сохранена в аудите."><textarea rows={3} className={inputClass} value={resolution.reason} onChange={(event) => setResolution({ ...resolution, reason: event.target.value })} /></Field><div className="flex gap-2"><Button disabled={resolution.reason.trim().length < 10 || adminClose.isPending || adminCancel.isPending} onClick={() => { const input = { commandId: crypto.randomUUID(), dealId: deal.id, reason: resolution.reason.trim() }; resolution.outcome === 'close' ? adminClose.mutate(input) : adminCancel.mutate(input); }}>Подтвердить решение</Button><Button variant="ghost" onClick={() => setResolution(null)}>Отмена</Button></div></div> : null}</Card></li>)}</ul>}</section>
    <section className="space-y-4"><h2 className="text-xl font-black">Журнал операций</h2>{ledger.isError ? <QueryFailed onRetry={() => void ledger.refetch()} error={ledger.error} /> : ledger.isLoading && !ledgerItems.length ? <Skeleton className="h-48" /> : !ledgerItems.length ? <EmptyState title="Операций пока нет" /> : <><p role="status" aria-live="polite">Показаны последние {ledgerItems.length} операций</p><ul className="divide-y divide-stitch-border rounded-2xl border border-stitch-border bg-stitch-surface">{ledgerItems.map((row) => <li key={row.id} className="flex flex-wrap items-center justify-between gap-2 p-4 text-sm"><span>{ledgerTypeLabel(row.type)}{walletSourceLabel(row.metadata?.sourceCommunityId, communityId) ? ` · ${walletSourceLabel(row.metadata?.sourceCommunityId, communityId)}` : ''}</span><span className="text-stitch-muted">{row.amount !== 0 ? `${row.amount > 0 ? '+' : ''}${row.amount} · ` : ''}{formatWhen(row.createdAt)}</span></li>)}</ul>{ledger.data?.nextCursor ? <Button type="button" onClick={() => setLedgerCursor(ledger.data.nextCursor ?? undefined)}>Показать ещё</Button> : null}</>}</section>
  </div></AppShell>;
}
