'use client';
import Link from 'next/link';
import { useState } from 'react';
import { AppShell } from '@/components/app-shell';
import { Badge, Button, Card, Notice, PageHeader, QueryFailed, Skeleton } from '@/components/ui';
import { trpc } from '@/lib/trpc/client';
import { useUzzCommunityId } from '@/lib/use-uzz-community';
import { clearUzzSessionFlag, uzzErrorMessage } from '@/lib/utils';

export default function ProfilePage() {
  const { isUzzAdmin } = useUzzCommunityId(); const me = trpc.auth.me.useQuery(undefined, { retry: false }); const link = trpc.identity.getLinkStatus.useQuery(undefined, { retry: false }); const [error, setError] = useState<string | null>(null);
  const start = trpc.identity.startTelegramLink.useMutation({ onSuccess: ({ deepLink }) => { if (deepLink) window.location.href = deepLink; else setError('Ссылка на бота не настроена. Обратитесь к администратору.'); }, onError: (err) => setError(uzzErrorMessage(err)) }); const logout = trpc.auth.logout.useMutation({ onSuccess: () => { clearUzzSessionFlag(); window.location.href = '/catalog'; } });
  return <AppShell><div className="space-y-8"><PageHeader eyebrow="Идентификация" title="Профиль">Email — единственный способ входа. Telegram связывает этот вход с добрыми делами в сообществе; публично ваш контакт не показывается до принятия заявки.</PageHeader>
    <div className="grid gap-4 md:grid-cols-2"><Card className="space-y-4"><h2 className="text-xl font-black">Аккаунт</h2>{me.isLoading ? <Skeleton className="h-20" /> : me.isError ? <QueryFailed onRetry={() => void me.refetch()} /> : <dl className="space-y-3 text-sm"><div><dt className="text-xs text-stitch-muted">Имя</dt><dd>{me.data?.displayName || 'Не указано'}</dd></div>{me.data?.communityName ? <div><dt className="text-xs text-stitch-muted">Сообщество</dt><dd>{me.data.communityName}</dd></div> : null}</dl>}<div className="flex flex-wrap gap-2"><Link href="/wallet" className="inline-flex min-h-11 items-center rounded-xl border border-stitch-border px-4 text-sm font-semibold">Кошелёк</Link>{isUzzAdmin ? <Link href="/admin" className="inline-flex min-h-11 items-center rounded-xl border border-stitch-border px-4 text-sm font-semibold">Админка</Link> : null}</div><Button variant="danger" disabled={logout.isPending} onClick={() => logout.mutate()}>Выйти</Button></Card>
      <Card className="space-y-4"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Связка</h2>{link.data?.linked ? <Badge tone="ok">Готово</Badge> : <Badge tone="warn">Не завершена</Badge>}</div>{link.isLoading ? <Skeleton className="h-20" /> : link.isError ? <QueryFailed onRetry={() => void link.refetch()} /> : <><dl className="space-y-3 text-sm"><div><dt className="text-xs text-stitch-muted">Email для входа</dt><dd className="break-all">{link.data?.email || 'Не указан'}</dd></div><div><dt className="text-xs text-stitch-muted">Telegram</dt><dd>{link.data?.telegramUsername ? `@${link.data.telegramUsername.replace(/^@/, '')}` : link.data?.telegramUserId ? 'Привязан' : 'Не привязан'}</dd></div></dl>{!link.data?.telegramUserId ? <Button disabled={start.isPending} onClick={() => start.mutate()}>{start.isPending ? 'Готовим ссылку…' : 'Привязать Telegram'}</Button> : <Notice tone="ok">Права, сделки и добрые дела сопоставлены с этим аккаунтом.</Notice>}{error ? <Notice tone="warn">{error}</Notice> : null}</>}</Card></div>
  </div></AppShell>;
}
